# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"  # Location of your requirements.txt
    schedule:
      interval: "weekly"  # Options: "daily", "weekly", "monthly"
      day: "monday"       # Optional: Specify the day of the week
      time: "04:00"       # Optional: Specify the time in UTC
      timezone: "UTC"     # Optional: Specify the timezone
    open-pull-requests-limit: 5  # Optional: Limit the number of open PRs
